[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "upstream-delineator"
version = "0.1.0"
description = "Delineate basins"

[tool.hatch.build.targets.wheel]
packages = ["src"]
