[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "upstream_delineator"
version = "0.1.1"
description = "Delineate basins"

[tool.hatch.build.targets.wheel]
packages = ["src"]
